In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/database.csv')

In [ ]:
df.sample(5)

,Date,Time,Latitude,Longitude,Type,Depth,Depth Error,Depth Seismic Stations,Magnitude,Magnitude Type,...,Magnitude Seismic Stations,Azimuthal Gap,Horizontal Distance,Horizontal Error,Root Mean Square,ID,Source,Location Source,Magnitude Source,Status
21596,02/06/2013,01:36:07,-11.809,165.301,Earthquake,10.0,NaN,31.0,5.5,MB,...,10.0,112.5,NaN,NaN,0.99,USP000JZ12,US,US,US,Reviewed
7266,11/12/1984,01:06:24,10.398,125.267,Earthquake,33.6,4.2,NaN,5.6,MW,...,NaN,NaN,NaN,NaN,1.10,USP00028ZN,US,US,HRV,Reviewed
4598,12/05/1977,14:13:52,-23.915,-175.950,Earthquake,33.0,NaN,NaN,5.9,MS,...,NaN,NaN,NaN,NaN,NaN,USP0000RY4,US,US,US,Reviewed
10303,12/27/1990,16:08:35,-22.725,-70.006,Earthquake,63.7,NaN,NaN,5.5,MW,...,NaN,NaN,NaN,NaN,0.90,USP0004JV1,US,US,HRV,Reviewed
5431,02/06/1980,05:50:55,-7.883,156.236,Earthquake,40.0,NaN,NaN,5.8,MB,...,NaN,NaN,NaN,NaN,NaN,USP00015B5,US,US,US,Reviewed

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23412 entries, 0 to 23411
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        23412 non-null  object
 1   Time                        23412 non-null  object
 2   Latitude                    23412 non-null  float64
 3   Longitude                   23412 non-null  float64
 4   Type                        23412 non-null  object
 5   Depth                       23412 non-null  float64
 6   Depth Error                 4461 non-null   float64
 7   Depth Seismic Stations      7097 non-null   float64
 8   Magnitude                   23412 non-null  float64
 9   Magnitude Type              23409 non-null  object
 10  Magnitude Error             327 non-null    float64
 11  Magnitude Seismic Stations  2564 non-null   float64
 12  Azimuthal Gap               7299 non-null   float64
 13  Horizontal Distance         1604 non-null   float64
 14  Horizontal Error            1156 non-null   float64
 15  Root Mean Square            17352 non-null  float64
 16  ID                          23412 non-null  object
 17  Source                      23412 non-null  object
 18  Location Source             23412 non-null  object
 19  Magnitude Source            23412 non-null  object
 20  Status                      23412 non-null  object
dtypes: float64(12), object(9)
memory usage: 3.8+ MB

In [ ]:
df.isnull().sum()

Date                              0
Time                              0
Latitude                          0
Longitude                         0
Type                              0
Depth                             0
Depth Error                   18951
Depth Seismic Stations        16315
Magnitude                         0
Magnitude Type                    3
Magnitude Error               23085
Magnitude Seismic Stations    20848
Azimuthal Gap                 16113
Horizontal Distance           21808
Horizontal Error              22256
Root Mean Square               6060
ID                                0
Source                            0
Location Source                   0
Magnitude Source                  0
Status                            0
dtype: int64

In [ ]:
data = df[['Date','Time','Latitude','Longitude','Magnitude','Depth']]
data.sample(5)

             Date      Time  Latitude  Longitude  Magnitude  Depth
5025   12/14/1978  19:25:59     0.536    126.022        6.0   60.0
14459  08/02/1999  01:06:38   -33.023    -70.153        5.5   95.4
673    05/11/1967  14:51:01    39.365     73.787        5.6   15.0
16039  11/02/2002  09:46:47     2.954     96.394        6.3   27.0
9584   08/12/1989  17:18:37    -7.259    -12.700        5.6   10.0

In [ ]:
import datetime
import time

In [ ]:
timestamp = []
for d, t in zip(data['Date'], data['Time']):
    try:
        ts = datetime.datetime.strptime(d+' '+t, '%m/%d/%Y %H:%M:%S')
        timestamp.append(time.mktime(ts.timetuple()))
    except ValueError:
        # print('ValueError')
        timestamp.append('ValueError')

timestamp = pd.Series(timestamp)
data['timestamp']= timestamp.values
data = data[data.timestamp != 'ValueError']

<ipython-input-8-7718ed5c8bea>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['timestamp']= timestamp.values

In [ ]:
data.drop(['Date','Time'],axis=1,inplace=True)

<ipython-input-9-59ea9644ef82>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.drop(['Date','Time'],axis=1,inplace=True)

In [ ]:
data.head()

   Latitude  Longitude  Magnitude  Depth    timestamp
0    19.246    145.616        6.0  131.6 -157630542.0
1     1.863    127.352        5.8   80.0 -157465811.0
2   -20.579   -173.972        6.2   20.0 -157355642.0
3   -59.076    -23.557        5.8   15.0 -157093817.0
4    11.938    126.427        5.8   15.0 -157026430.0

In [ ]:

data.head()

   Latitude  Longitude  Magnitude  Depth    timestamp
0    19.246    145.616        6.0  131.6 -157630542.0
1     1.863    127.352        5.8   80.0 -157465811.0
2   -20.579   -173.972        6.2   20.0 -157355642.0
3   -59.076    -23.557        5.8   15.0 -157093817.0
4    11.938    126.427        5.8   15.0 -157026430.0

In [ ]:
x= data[['Latitude','Longitude','timestamp']]
y = data[['Magnitude','Depth']]

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)
y_test

(18727, 3) (4682, 3) (18727, 2) (4682, 2)

       Magnitude  Depth
13121        5.5   74.3
17921        6.3   26.0
3419         5.6   33.0
20803        5.8   16.0
15057        5.5   10.0
...          ...    ...
10828        6.3   10.0
22412        5.6   10.0
18333        6.9   35.0
11266        6.0  600.9
9152         5.7   27.9

[4682 rows x 2 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
ft = MinMaxScaler()
x_train = ft.fit_transform(x_train)
x_test= ft.transform(x_test)

In [ ]:
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(16,activation='relu',input_shape=(3,)))
model.add(Dense(16,activation='relu'))
model.add(Dense(2))

model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_9 (Dense)             (None, 16)                64

 dense_10 (Dense)            (None, 16)                272

 dense_11 (Dense)            (None, 2)                 34

=================================================================
Total params: 370
Trainable params: 370
Non-trainable params: 0
_________________________________________________________________

In [ ]:
# x_train = np.asarray(x_train).astype(np.float32)
# y_train = np.asarray(y_train).astype(np.float32)
# x_test = np.asarray(x_test).astype(np.float32)
# y_test = np.asarray(y_test).astype(np.float32)

model.fit(x_train,y_train,batch_size=10, epochs=20,verbose=1, validation_data=(x_test, y_test))

Epoch 1/20
1873/1873 [==============================] - 7s 4ms/step - loss: 8762.3994 - accuracy: 0.9784 - val_loss: 7954.2827 - val_accuracy: 0.9814
Epoch 2/20
1873/1873 [==============================] - 8s 4ms/step - loss: 7705.6440 - accuracy: 0.9811 - val_loss: 7751.7256 - val_accuracy: 0.9814
Epoch 3/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7653.8638 - accuracy: 0.9811 - val_loss: 7725.6230 - val_accuracy: 0.9814
Epoch 4/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7634.8159 - accuracy: 0.9811 - val_loss: 7704.5254 - val_accuracy: 0.9814
Epoch 5/20
1873/1873 [==============================] - 8s 4ms/step - loss: 7614.7168 - accuracy: 0.9811 - val_loss: 7676.3804 - val_accuracy: 0.9814
Epoch 6/20
1873/1873 [==============================] - 8s 4ms/step - loss: 7587.5952 - accuracy: 0.9811 - val_loss: 7639.7939 - val_accuracy: 0.9814
Epoch 7/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7552.4932 - accuracy: 0.9811 - val_loss: 7598.9971 - val_accuracy: 0.9814
Epoch 8/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7513.4829 - accuracy: 0.9811 - val_loss: 7552.2529 - val_accuracy: 0.9814
Epoch 9/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7470.1450 - accuracy: 0.9811 - val_loss: 7504.3203 - val_accuracy: 0.9814
Epoch 10/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7429.3936 - accuracy: 0.9811 - val_loss: 7463.7378 - val_accuracy: 0.9814
Epoch 11/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7389.1616 - accuracy: 0.9811 - val_loss: 7423.6226 - val_accuracy: 0.9814
Epoch 12/20
1873/1873 [==============================] - 8s 4ms/step - loss: 7347.7002 - accuracy: 0.9811 - val_loss: 7379.7231 - val_accuracy: 0.9814
Epoch 13/20
1873/1873 [==============================] - 8s 4ms/step - loss: 7299.1929 - accuracy: 0.9811 - val_loss: 7326.6572 - val_accuracy: 0.9814
Epoch 14/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7246.2705 - accuracy: 0.9811 - val_loss: 7277.9302 - val_accuracy: 0.9814
Epoch 15/20
1873/1873 [==============================] - 8s 4ms/step - loss: 7194.3022 - accuracy: 0.9811 - val_loss: 7229.2227 - val_accuracy: 0.9814
Epoch 16/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7145.6509 - accuracy: 0.9811 - val_loss: 7190.4146 - val_accuracy: 0.9814
Epoch 17/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7103.9375 - accuracy: 0.9811 - val_loss: 7150.7046 - val_accuracy: 0.9814
Epoch 18/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7068.0396 - accuracy: 0.9811 - val_loss: 7120.7637 - val_accuracy: 0.9814
Epoch 19/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7036.7192 - accuracy: 0.9811 - val_loss: 7089.9019 - val_accuracy: 0.9814
Epoch 20/20
1873/1873 [==============================] - 7s 4ms/step - loss: 7008.1538 - accuracy: 0.9811 - val_loss: 7063.7798 - val_accuracy: 0.9814

In [ ]:
[test_loss, test_acc] = model.evaluate(x_test, y_test)

147/147 [==============================] - 0s 2ms/step - loss: 7063.7793 - accuracy: 0.9814

In [ ]:
model.predict(x_test)

147/147 [==============================] - 0s 2ms/step

array([[  5.8534403,  61.469933 ],
       [  6.1243773,  67.35326  ],
       [  5.8311787, 127.75626  ],
       ...,
       [  6.448468 ,  73.83522  ],
       [  6.106562 ,  66.38978  ],
       [  5.8016768, 125.03998  ]], dtype=float32)